package com.zhu.easyspring.entity;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_code
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    private String permissionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_name
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.parent
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    private String parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_code
     *
     * @return the value of permission.permission_code
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_code
     *
     * @param permissionCode the value for permission.permission_code
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_name
     *
     * @return the value of permission.permission_name
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_name
     *
     * @param permissionName the value for permission.permission_name
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.parent
     *
     * @return the value of permission.parent
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.parent
     *
     * @param parent the value for permission.parent
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }
}