package com.zhu.easyspring.entity;

import org.codehaus.jackson.annotate.JsonProperty;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.code
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.type
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.url
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.icon
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.permission
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.parent
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    @JsonProperty("_parentId")
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.avaliable
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    private Integer avaliable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.code
     *
     * @return the value of resource.code
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.code
     *
     * @param code the value for resource.code
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.type
     *
     * @return the value of resource.type
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.type
     *
     * @param type the value for resource.type
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.url
     *
     * @return the value of resource.url
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.url
     *
     * @param url the value for resource.url
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.icon
     *
     * @return the value of resource.icon
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.icon
     *
     * @param icon the value for resource.icon
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.permission
     *
     * @return the value of resource.permission
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.permission
     *
     * @param permission the value for resource.permission
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.parent
     *
     * @return the value of resource.parent
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.parent
     *
     * @param parent the value for resource.parent
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.avaliable
     *
     * @return the value of resource.avaliable
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public Integer getAvaliable() {
        return avaliable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.avaliable
     *
     * @param avaliable the value for resource.avaliable
     *
     * @mbggenerated Mon Mar 16 14:20:44 CST 2015
     */
    public void setAvaliable(Integer avaliable) {
        this.avaliable = avaliable;
    }
}