package com.zhu.easyspring.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.code
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.permission_ids
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    private String permissionIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.code
     *
     * @return the value of role.code
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.code
     *
     * @param code the value for role.code
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.permission_ids
     *
     * @return the value of role.permission_ids
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public String getPermissionIds() {
        return permissionIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.permission_ids
     *
     * @param permissionIds the value for role.permission_ids
     *
     * @mbggenerated Sat Mar 14 21:25:39 CST 2015
     */
    public void setPermissionIds(String permissionIds) {
        this.permissionIds = permissionIds == null ? null : permissionIds.trim();
    }
}